name: notes_app
description: Notes app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  sqflite: ^2.0.2
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.1.0
  build_runner: ^2.1.7
  test: ^1.19.5
  bloc_test: ^9.0.3

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
