name: notes_repository
description: A repository that handles notes requests.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  notes_api:
    path: ../notes_api

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.4
